### ISSUE TITLE
env var AWS_REGION can be used in task 

### ISSUE THREAD

**Issue by cschar** [arch-inc/amazon-lightsail-containers-test#1]
https://github.com/arch-inc/amazon-lightsail-containers-test/blob/6c3b299cfca876ae206bec44794822cd7b09d83f/.github/workflows/deploy.yml#L41

Very useful example, thank you :) !

**Comment by arcatdmz** [comment]
Glad this helped!

**Comment by arcatdmz** [comment]
Ah, okay, this line could be replaced with `${{ env.AWS_REGION }}`.
